### PR TITLE
Updated new help info

### PR DESCRIPTION
**Pull request by nirlipo**
Added more info an a gif to showcase how to use planimation

### CODE REVIEW

**Comment by nirlipo** [comment]
@haz is this the intended process for updating plugins? PR from a fork?

**Comment by haz** [comment]
For those trusted with write access, either branch or fork with a PR. For those we don't know, fork.

Either way, I need to know so I can update the git submodule in the editor.

**Comment by nirlipo** [comment]
Perfect, note that when you migrated to github, we all lost our write rights to the repos containing the existing plugins

**Comment by haz** [comment]
Just gave everyone write access. The actual owners & permissions couldn't be migrated, so now everyone in the AI Planning group has write access to all the repos. We can change it back if it becomes a problem.

**Pull request merged**
